// canada/lang.js
// Language switcher for Canada pages

const translations = {
  en: {
      'blogHub.hero.h1': 'Insights & Updates',
      'blogHub.hero.desc': 'Explore trends, tips, and practical insights in structural engineering and construction execution.',
      'blogHub.filt.client': 'Client Guide',
      'blogHub.filt.construction': 'Construction Tips',
      'blogHub.filt.green': 'Green Building',
      'blogHub.grid.count': '21 articles',
    // BlogHub new articles (c13–c21)
    'blogHub.c13.rt': '8 min read',
    'blogHub.c13.h3': 'Underpinning in Ontario: Methods, OHSA Requirements & Adjacent Property Rights',
    'blogHub.c13.p': 'When Ontario excavations threaten adjacent building foundations, underpinning is required. Learn the pit, pile, and micropile methods, OHSA obligations, and how disputes with neighbours are handled.',
    'blogHub.c14.rt': '7 min read',
    'blogHub.c14.h3': 'Toronto ePLAN Submission Guide: Drawing Standards, Documents & Review Timeline',
    'blogHub.c14.p': "Toronto's ePLAN portal requires digital submission for all building permit applications. Learn drawing standards, required documents, common rejection reasons, and realistic review timelines.",
    'blogHub.c15.rt': '8 min read',
    'blogHub.c15.h3': 'Ontario Building Permit Process: From Application to Occupancy Permit',
    'blogHub.c15.p': 'A complete walkthrough of the Ontario building permit process under the Building Code Act — application requirements, statutory review timelines, mandatory inspections, and occupancy permits.',
    'blogHub.c16.rt': '7 min read',
    'blogHub.c16.h3': 'Tarion New Home Warranty & Structural Engineering Obligations in Ontario',
    'blogHub.c16.p': "Ontario's Tarion warranty provides 7-year Major Structural Defect coverage. Learn what qualifies as an MSD, how the claim process works, and when a structural engineer is needed.",
    'blogHub.c17.rt': '8 min read',
    'blogHub.c17.h3': 'CSA Standards in Ontario Structural Engineering: A23.3, S16, O86 & S6 Explained',
    'blogHub.c17.p': 'A practical guide to the CSA standards every Ontario structural engineer uses — concrete (A23.3), steel (S16), wood (O86), and bridges (S6) — and how they relate to the OBC and NBCC.',
    'blogHub.c18.rt': '7 min read',
    'blogHub.c18.h3': 'OBC Permit Types in Ontario: Building, Conditional, Demolition & Change of Use',
    'blogHub.c18.p': 'A complete guide to Ontario Building Code permit types — when each applies, what drawings and documents are required, and how permit timelines work across Ontario municipalities.',
    'blogHub.c19.rt': '8 min read',
    'blogHub.c19.h3': 'Structural Renovations in Ontario: OBC Compliance, Heritage Buildings & Retrofit Engineering',
    'blogHub.c19.p': 'Structural renovations to existing Ontario buildings require navigating OBC retrofit compliance, heritage designations, and change-of-use requirements. This guide explains the engineering approach.',
    'blogHub.c20.rt': '8 min read',
    'blogHub.c20.h3': 'Seismic Retrofitting in Ontario: NBCC 2020 Triggers, Retrofit Methods & Post-Disaster Buildings',
    'blogHub.c20.p': 'When seismic retrofitting is required in Ontario, how NBCC 2020 seismic provisions apply to existing buildings, and engineering approaches to upgrading unreinforced masonry, concrete frames, and steel buildings.',
    'blogHub.c21.rt': '7 min read',
    'blogHub.c21.h3': 'Structural Peer Review in Ontario: PEO Requirements, Toronto Building Thresholds & Process',
    'blogHub.c21.p': 'When Ontario projects require independent structural peer review, what PEO and Toronto Building Division require, how the two-round review process works, and how to select a qualified reviewer.',
    'brand.eng': 'ENG',
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.services': 'Services',
    'nav.projects': 'Projects',
    'nav.contact': 'Contact Us',
    'hero.tag': 'Toronto Structural Engineering',
    'hero.sub': 'Asvakas Engineering helps owners and developers deliver safer, smarter projects across Canada.',
    'hero.cta1': 'Request Assessment',
    'hero.cta2': 'Explore Services',
    'home.about.label': 'About Asvakas',
    'home.about.h2': 'New company, decades of proven structural experience behind every project.',
    'home.about.p': 'As a startup firm built by seasoned engineers, Asvakas delivers fresh solutions with deep construction and design expertise, plus modern client service.',
    'home.about.cta': 'Get to Know Us',
    'stat.years': 'Years Experience',
    'stat.projects': 'Projects Completed',
    'stat.sat': 'Client Satisfaction',
    'stat.success': 'Success Rate',
    'svc.pill': 'Our Services',
    'svc.h2': 'We Build Everything You Need',
    'svc.sub': 'From temporary works and structural design to OBC compliance — our engineers deliver precision across every discipline.',
    'svc.cat.structural': 'Structural Engineering',
    'svc.01.h': 'Structural Renovation',
    'svc.01.p': 'Repair, renovation, addition, opening, steel and concrete fixes, and masonry rehab.',
    'svc.02.h': 'Structural Design',
    'svc.02.p': 'Wood, brick masonry, steel, concrete, and composite structure design to NBC/OBC standards.',
    'svc.03.h': 'Supervision & Consultancy',
    'svc.03.p': 'Peer review, supervision, special inspection, assessment and damage evaluation.',
    'svc.cat.obc': 'OBC Compliance Inspections',
    'svc.04.h': 'Exterior Building Inspection',
    'svc.04.p': 'OBC Part 11 existing building inspections, condition assessment, and building permit filing.',
    'svc.05.h': 'Parking Structure Assessment',
    'svc.05.p': 'Structural condition surveys, repair planning, and permit documentation for parking structures.',
    'svc.06.h': 'Sidewalk & Exterior Works',
    'svc.06.p': 'Sidewalk inspection, restoration, and repair with safe and code-compliant pedestrian solutions.',
    'svc.cat.temp': 'Temporary Works Engineering',
    'svc.07.h': 'Bridge & Building Erection Plans',
    'svc.07.p': 'Detailed erection staging, sequencing, and structural support design for buildings and bridges.',
    'svc.08.h': 'Water Diversion & Cofferdams',
    'svc.08.p': 'Temporary works engineering for watercourse rerouting, cofferdam design and stabilization.',
    'svc.09.h': 'Bridge Demolition & Removal',
    'svc.09.p': 'Safe, code-compliant bridge dismantling with detailed demolition methodology and logistics.',
    'svc.cat.specialty': 'Specialty Engineering',
    'svc.10.h': 'Roof Repair & Safety',
    'svc.10.p': 'Roof dunnage, safety railings, parapets, bulkhead renovation, and roof system repair.',
    'svc.11.h': 'Anchorage & Connection',
    'svc.11.p': 'Design of concrete anchors, steel/wood connections, brick masonry anchorage systems.',
    'svc.12.h': 'Formwork Design',
    'svc.12.p': 'Slab formwork, sidewalk overhead protection, and renovation formwork engineering.',
    'svc.cat.forensic': 'Forensic Engineering',
    'svc.13.h': 'Forensic Structural Investigation',
    'svc.13.p': 'On-site investigation of structural distress, collapse, or unexpected movement to determine root cause.',
    'svc.14.h': 'Failure Analysis & Expert Reports',
    'svc.14.p': 'Detailed technical analysis of structural failures for insurance claims, legal proceedings, and code compliance disputes.',
    'svc.15.h': 'Expert Witness & Testimony',
    'svc.15.p': 'Professional engineering testimony and expert witness services for construction litigation and arbitration proceedings.',
    'svc.cat.construction': 'Construction Services',
    'svc.16.h': 'Cost Estimation',
    'svc.16.p': 'Accurate quantity takeoffs and cost projections for structural scopes, helping owners and contractors budget with confidence.',
    'svc.17.h': 'Project Scheduling',
    'svc.17.p': 'Comprehensive construction schedules and critical path analysis to keep complex structural projects on track from start to finish.',
    'svc.18.h': 'Construction Administration',
    'svc.18.p': 'On-site engineering oversight and shop drawing review throughout construction to ensure structural compliance.',
    'why.pill': 'Our Great Values',
    'why.h2': 'Why Asvakas?',
    'why.cta': 'Get to Know Us →',
    'why.tagline': 'Trusted by property owners and developers across Canada, built for precision, and designed to deliver reliable structural solutions that stand the test of time.',
    'why.01.h': 'Proven Engineering Quality',
    'why.01.p': 'Our team brings 35+ years of combined engineering experience to every inspection, design, and renovation project.',
    'why.02.h': 'On-Time Delivery',
    'why.02.p': 'We value your deadlines — every permit filing, inspection report, and design deliverable is completed on schedule.',
    'why.03.h': 'Safety First Approach',
    'why.03.p': 'We rigorously follow OBC/NBC codes and OH&S standards to protect both your property and everyone on site.',
    'why.04.h': 'Modern Engineering Solutions',
    'why.04.p': 'Fresh perspectives backed by experience — we apply innovative methods to deliver efficient, cost-effective structural outcomes.',
    'proj.featured.h2': 'Featured Projects',
    'proj.featured.sub': 'A closer look at our craftsmanship, showcasing quality in every project.',
    'proc.pill': 'How We Work',
    'proc.h2': 'Our Work Process',
    'proc.sub': 'A proven process to bring your ideas to life turns concepts into reality through strategic planning and execution.',
    'proc.01.h': 'Consultation & Planning',
    'proc.01.p': 'Understanding your needs, budget, and vision ensures your project aligns with your goals while staying within practical limits.',
    'proc.02.h': 'Design & Architecture',
    'proc.02.p': 'Visualizing the project with practical design and structural precision aligns aesthetics, function, and OBC compliance.',
    'proc.03.h': 'Construction & Management',
    'proc.03.p': 'From site coordination to quality control, we guide execution with consistency so the final build meets every requirement.',
    'test.pill': 'Testimonials',
    'test.h2': 'What Our Clients Say',
    'test.sub': 'Hear from teams who built with us and how we translated complex engineering requirements into results.',
    'test.1.quote': 'Asvakas exceeded all expectations. Their team turned a difficult compliance scope into a smooth, well-managed delivery.',
    'test.1.body': 'From initial inspection to final sign-off, communication was clear and every milestone was handled with precision.',
    'test.1.role': 'Residential Client, Toronto',
    'test.2.quote': 'From consultation to handover, their engineers were responsive, practical, and deeply knowledgeable.',
    'test.2.body': 'They coordinated our office renovation with contractors and inspectors while keeping timeline risks under control.',
    'test.2.role': 'Commercial Developer, Toronto',
    'test.3.quote': 'Their temporary works strategy saved us from major delays during excavation and underpinning.',
    'test.3.body': 'The documentation was clean, permit-ready, and easy for our site team to execute without confusion.',
    'test.3.role': 'General Contractor, Ontario',
    'test.4.quote': 'We finally found an engineering partner that balances technical depth with real-world constructability.',
    'test.4.body': 'Their team anticipated issues early and helped us make smarter decisions before costs escalated.',
    'test.4.role': 'Property Manager, Vancouver',
    // ...add more keys as needed
  },
  fr: {
    // FAQ PAGE
    'faq.hero.pill': 'Centre d’aide',
    'faq.hero.h1': 'FAQ Génie Structurel — Ontario & Toronto',
    'faq.hero.p': 'Réponses aux questions les plus courantes sur le génie structurel en Ontario — permis CCO, revue PEO, inspections de façade, étaiement, fondations et services d’expert.',
    'faq.meta.pill': 'FAQ',
    'faq.meta.updated': 'Mise à jour avril 2026 · Par Asvakas Engineering',
    'faq.toc.h': 'Aller à un sujet',
    'faq.toc.1': 'Général — Ingénieurs structurels en Ontario',
    'faq.toc.2': 'Code du bâtiment de l’Ontario & Permis',
    'faq.toc.3': 'Revue PEO & Administration',
    'faq.toc.4': 'Fondations, sous-œuvre & étaiement',
    'faq.toc.5': 'Génie judiciaire & expert',
    'faq.toc.6': 'Coûts & Délais',
    'faq.s1.h': 'Général — Ingénieurs structurels en Ontario',
    'faq.s1.q1': 'Que fait un ingénieur structurel en Ontario ?',
    'faq.s1.a1': 'Un ingénieur structurel en Ontario conçoit et évalue les éléments porteurs des bâtiments — fondations, colonnes, poutres, dalles, murs et contreventements. Les P.Eng. inscrits auprès de l’OIQ scellent les plans pour les permis, effectuent la revue de chantier, rédigent des rapports d’expertise et témoignent en cour.',
    'faq.s1.q2': 'L’ingénierie structurelle est-elle réglementée en Ontario ?',
    'faq.s1.a2': 'Oui. La pratique de l’ingénierie en Ontario est réglementée par la Loi sur les ingénieurs professionnels, administrée par l’OIQ. Toute personne pratiquant l’ingénierie structurelle doit détenir un permis P.Eng. ou être EIT sous supervision. Le scellement des plans pour permis exige un P.Eng. en règle.',
    'faq.s1.q3': 'Asvakas Engineering est-elle autorisée à exercer en Ontario ?',
    'faq.s1.a3': 'Oui. Nos dirigeants détiennent des permis P.Eng. en règle et sont autorisés à sceller des plans, déposer auprès des municipalités et fournir des services d’expert partout en Ontario.',
    'faq.s2.h': 'Code du bâtiment de l’Ontario & Permis',
    'faq.s2.q1': 'Qu’est-ce que le Code du bâtiment de l’Ontario (CCO) ?',
    'faq.s2.a1': 'Le CCO est le règlement 332/12 pris en vertu de la Loi sur le bâtiment. Il fixe les exigences minimales pour tous les bâtiments — solidité, sécurité incendie, accessibilité, efficacité énergétique. Il référence les normes CSA (A23.3 béton, S16 acier, O86 bois). Les bâtiments doivent respecter l’édition du CCO en vigueur lors de la demande de permis.',
    'faq.s2.q2': 'Ai-je besoin d’un permis pour des travaux structurels ?',
    'faq.s2.a2': 'Oui, dans la plupart des cas. La Loi sur le bâtiment exige un permis pour toute nouvelle construction, ajout ou modification structurelle — ajout d’étage, modification de murs porteurs, sous-œuvre, etc. Déposez votre demande avec plans scellés auprès de votre municipalité.',
    'faq.s2.q3': 'Quelle est la différence entre le CNB et le CCO ?',
    'faq.s2.a3': 'Le Code national du bâtiment (CNB) est un code modèle sans force de loi. Le CCO est le règlement adopté par l’Ontario, intégrant le CNB et des dispositions propres à l’Ontario. En cas de divergence, le CCO prévaut.',
    'faq.s2.q4': 'Comment obtenir un permis à Toronto ?',
    'faq.s2.a4': 'Déposez via le système ePLAN de la Ville de Toronto avec formulaires, frais (~20–30 $/1 000 $ de travaux) et plans conformes au CCO. Délai : 10–20 jours ouvrables (résidentiel), 40–80 jours (commercial).',
    'faq.s3.h': 'Revue PEO & Administration de chantier',
    'faq.s3.q1': 'Qu’est-ce que la revue générale PEO (revue de chantier) ?',
    'faq.s3.a1': 'La revue générale PEO est l’inspection sur site par l’ingénieur responsable pour vérifier la conformité aux plans scellés. Obligatoire pour les bâtiments de la partie 3 et plusieurs types de la partie 1 du CCO. À la fin, l’ingénieur remet un certificat de revue générale (Annexe 2, Div. C) — condition pour l’occupation.',
    'faq.s3.q2': 'Que sont les plans d’atelier et pourquoi l’ingénieur les révise-t-il ?',
    'faq.s3.a2': 'Les plans d’atelier sont des dessins détaillés préparés par les entrepreneurs pour la fabrication. L’ingénieur les révise pour s’assurer qu’ils respectent l’intention des plans scellés. Le tampon signifie « conforme à l’intention » — pas que l’ingénieur garantit la fabrication.',
    'faq.s4.h': 'Fondations, sous-œuvre & étaiement',
    'faq.s4.q1': 'Qu’est-ce que la sous-œuvre et quand est-elle requise ?',
    'faq.s4.a1': 'La sous-œuvre renforce ou approfondit une fondation existante, par exemple si un voisin creuse plus profond, si la fondation est insuffisante ou en cas de tassement. La conception doit être scellée par un P.Eng. et approuvée avant travaux.',
    'faq.s4.q2': 'Quel étaiement est requis pour les excavations ?',
    'faq.s4.a2': 'Le règlement 213/91 exige des plans d’étaiement scellés par un P.Eng. si l’excavation est adjacente à un bâtiment et que le sol ne peut être maintenu en sécurité autrement. Systèmes courants : palplanches, pieux, murs cloués, etc.',
    'faq.s4.q3': 'Quelles sont les exigences d’inspection de façade en Ontario ?',
    'faq.s4.a3': 'Pas de programme provincial, mais le CCO et la Ville de Toronto exigent le maintien en bon état. Des inspections peuvent être ordonnées après signalement de défaillances.',
    'faq.s5.h': 'Génie judiciaire & expert',
    'faq.s5.q1': 'Qu’est-ce que la règle 53.03 pour les experts en Ontario ?',
    'faq.s5.a1': 'La règle 53.03 régit les experts en cour civile : rapport écrit, reconnaissance du devoir d’impartialité, divulgation des intérêts financiers. La Cour suprême a confirmé que l’impartialité est essentielle.',
    'faq.s5.q2': 'Qu’est-ce qu’une enquête structurelle judiciaire ?',
    'faq.s5.a2': 'Une enquête judiciaire détermine la cause d’une défaillance structurelle. Elle inclut : examen des plans, inspection, essais matériaux, analyse et rapport écrit avec recommandations.',
    'faq.s6.h': 'Coûts & Délais',
    'faq.s6.q1': 'Combien coûte un ingénieur structurel en Ontario ?',
    'faq.s6.a1': 'Évaluations résidentielles : 1 500–5 000 $. Plans pour ajouts : 3 000–12 000 $. Conception complète : 25–60 $/m². Revue générale : incluse ou 1 500–5 000 $. Expertise : 175–350 $/h.',
    'faq.s6.q2': 'Comment démarrer avec Asvakas Engineering ?',
    'faq.s6.a2': 'Contactez-nous via la page contact. Décrivez votre projet, lieu et échéance. Nous fournirons une proposition sous 1–2 jours ouvrables.',
    'faq.cta.h': 'Vous ne trouvez pas votre question ?',
    'faq.cta.p': 'Contactez directement Asvakas Engineering. Nos ingénieurs P.Eng. répondent à toutes les demandes sous 1–2 jours ouvrables.',
    'faq.cta.btn': 'Poser une question',
    'faq.sidebar.cta.h': 'Besoin d’un P.Eng. en Ontario ?',
    'faq.sidebar.cta.p': 'Ingénieurs structurels agréés OIQ pour permis CCO, revue de chantier, expertise et témoignage.',
    'faq.sidebar.cta.btn': 'Contactez-nous →',
    'faq.sidebar.kb.h': 'Base de connaissances',
    // FOOTER
    'footer.sub.heading': 'Abonnez-vous aux mises à jour',
    'footer.sub.text': 'Recevez des actualités CCO et des analyses en génie structurel.',
    'footer.sub.btn': 'S’abonner',
    'footer.col1.h': 'Entreprise',
    'footer.col2.h': 'Réseaux sociaux',
    'footer.col3.h': 'Support',
    'footer.link.home': 'Accueil',
    'footer.link.about': 'À propos',
    'footer.link.services': 'Services',
    'footer.link.projects': 'Projets',
    'footer.link.blog': 'Blogue',
    'footer.link.faq': 'FAQ',
    'footer.link.help': 'Centre d’aide',
    'footer.copy': '© 2026 Asvakas Inc. Tous droits réservés.',
    'footer.privacy': 'Politique de confidentialité & Conditions d’utilisation',
    // ...add more keys as needed
      'blogHub.hero.h1': 'Aperçus & Actualités',
      'blogHub.hero.desc': 'Découvrez les tendances, conseils et analyses pratiques en génie structurel et exécution de la construction.',
      'blogHub.filt.client': 'Guide client',
      'blogHub.filt.construction': 'Conseils construction',
      'blogHub.filt.green': 'Bâtiment durable',
      'blogHub.grid.count': '21 articles',
    // BlogHub nouveaux articles (c13–c21)
    'blogHub.c13.rt': '8 min de lecture',
    'blogHub.c13.h3': 'Sous-œuvre en Ontario : méthodes, exigences de la LSST et droits des propriétés adjacentes',
    'blogHub.c13.p': "Lorsque les excavations en Ontario menacent les fondations des bâtiments voisins, une sous-œuvre est requise. Découvrez les méthodes de fosse, de pieu, de micropieu, les obligations de la LSST et la gestion des litiges de voisinage.",
    'blogHub.c14.rt': '7 min de lecture',
    'blogHub.c14.h3': 'Guide de soumission ePLAN Toronto : normes de dessin, documents et délais d’examen',
    'blogHub.c14.p': "Le portail ePLAN de Toronto exige une soumission numérique pour toutes les demandes de permis de construire. Découvrez les normes de dessin, les documents requis, les motifs de rejet courants et les délais d’examen réalistes.",
    'blogHub.c15.rt': '8 min de lecture',
    'blogHub.c15.h3': 'Processus de permis de construire en Ontario : de la demande à l’occupation',
    'blogHub.c15.p': "Un aperçu complet du processus de permis de construire en Ontario selon la Loi sur le bâtiment — exigences de la demande, délais d’examen, inspections obligatoires et permis d’occupation.",
    'blogHub.c16.rt': '7 min de lecture',
    'blogHub.c16.h3': 'Garantie Tarion et obligations d’ingénierie structurelle en Ontario',
    'blogHub.c16.p': "La garantie Tarion de l’Ontario offre une couverture MSD de 7 ans. Découvrez ce qui constitue un MSD, le processus de réclamation et quand un ingénieur structurel est requis.",
    'blogHub.c17.rt': '8 min de lecture',
    'blogHub.c17.h3': 'Normes CSA en ingénierie structurelle en Ontario : A23.3, S16, O86 et S6',
    'blogHub.c17.p': "Un guide pratique des normes CSA utilisées par les ingénieurs structurels en Ontario — béton (A23.3), acier (S16), bois (O86), ponts (S6) — et leur lien avec le CCO et le CNBC.",
    'blogHub.c18.rt': '7 min de lecture',
    'blogHub.c18.h3': 'Types de permis CCO en Ontario : construction, conditionnel, démolition et changement d’usage',
    'blogHub.c18.p': "Guide complet des types de permis du Code du bâtiment de l’Ontario — quand chacun s’applique, quels plans et documents sont requis, et comment fonctionnent les délais dans les municipalités.",
    'blogHub.c19.rt': '8 min de lecture',
    'blogHub.c19.h3': 'Rénovations structurelles en Ontario : conformité CCO, bâtiments patrimoniaux et ingénierie de réhabilitation',
    'blogHub.c19.p': "Les rénovations structurelles des bâtiments existants en Ontario nécessitent la conformité au CCO, la gestion des désignations patrimoniales et des changements d’usage. Ce guide explique l’approche d’ingénierie.",
    'blogHub.c20.rt': '8 min de lecture',
    'blogHub.c20.h3': 'Renforcement parasismique en Ontario : déclencheurs CNBC 2020, méthodes de réhabilitation et bâtiments post-catastrophe',
    'blogHub.c20.p': "Quand le renforcement parasismique est requis en Ontario, comment les dispositions du CNBC 2020 s’appliquent aux bâtiments existants, et les approches d’ingénierie pour la mise à niveau de la maçonnerie, du béton et de l’acier.",
    'blogHub.c21.rt': '7 min de lecture',
    'blogHub.c21.h3': 'Révision par les pairs en ingénierie structurelle en Ontario : exigences de l’OIQ, seuils de Toronto et processus',
    'blogHub.c21.p': "Quand les projets en Ontario nécessitent une révision structurelle indépendante, ce qu’exigent l’OIQ et la division du bâtiment de Toronto, comment fonctionne le processus en deux étapes et comment choisir un réviseur qualifié.",
    'brand.eng': 'ING',
    'nav.home': 'Accueil',
    'nav.about': 'À propos',
    'nav.services': 'Services',
    'nav.projects': 'Projets',
    'nav.contact': 'Contactez-nous',
    'hero.tag': 'Génie structurel à Toronto',
    'hero.sub': 'Asvakas Engineering aide les propriétaires et les promoteurs à réaliser des projets plus sûrs et plus intelligents à travers le Canada.',
    'hero.cta1': 'Demander une évaluation',
    'hero.cta2': 'Explorer les services',
    'home.about.label': 'À propos d’Asvakas',
    'home.about.h2': 'Nouvelle entreprise, des décennies d’expérience structurelle éprouvée derrière chaque projet.',
    'home.about.p': 'En tant que jeune entreprise fondée par des ingénieurs chevronnés, Asvakas propose des solutions innovantes avec une expertise approfondie en construction et en conception, ainsi qu’un service client moderne.',
    'home.about.cta': 'Faites connaissance avec nous',
    'stat.years': 'Années d’expérience',
    'stat.projects': 'Projets réalisés',
    'stat.sat': 'Satisfaction client',
    'stat.success': 'Taux de réussite',
    'svc.pill': 'Nos services',
    'svc.h2': 'Nous construisons tout ce dont vous avez besoin',
    'svc.sub': 'Des travaux temporaires à la conception structurelle en passant par la conformité au CCO — nos ingénieurs offrent la précision dans chaque discipline.',
    'svc.cat.structural': 'Génie structurel',
    'svc.01.h': 'Rénovation structurelle',
    'svc.01.p': 'Réparation, rénovation, ajout, ouverture, réparations en acier et béton, et réhabilitation de maçonnerie.',
    'svc.02.h': 'Conception structurelle',
    'svc.02.p': 'Conception de structures en bois, maçonnerie, acier, béton et composite selon les normes NBC/CCO.',
    'svc.03.h': 'Supervision & Conseil',
    'svc.03.p': 'Révision par les pairs, supervision, inspection spéciale, évaluation et expertise des dommages.',
    'svc.cat.obc': 'Inspections de conformité CCO',
    'svc.04.h': 'Inspection extérieure du bâtiment',
    'svc.04.p': 'Inspections des bâtiments existants selon la partie 11 du CCO, évaluation de l’état et dépôt de permis.',
    'svc.05.h': 'Évaluation des stationnements',
    'svc.05.p': 'Enquêtes sur l’état structurel, planification des réparations et documentation des permis pour les stationnements.',
    'svc.06.h': 'Trottoirs & Travaux extérieurs',
    'svc.06.p': 'Inspection, restauration et réparation des trottoirs avec des solutions piétonnes sûres et conformes au code.',
    'svc.cat.temp': 'Génie des ouvrages temporaires',
    'svc.07.h': 'Plans de montage de ponts & bâtiments',
    'svc.07.p': 'Planification détaillée du montage, séquençage et conception du support structurel pour bâtiments et ponts.',
    'svc.08.h': 'Déviation d’eau & batardeaux',
    'svc.08.p': 'Ingénierie des ouvrages temporaires pour le détournement de cours d’eau, la conception et la stabilisation de batardeaux.',
    'svc.09.h': 'Démolition & enlèvement de ponts',
    'svc.09.p': 'Démantèlement de ponts conforme au code avec méthodologie de démolition détaillée et logistique.',
    'svc.cat.specialty': 'Génie spécialisé',
    'svc.10.h': 'Réparation & sécurité des toits',
    'svc.10.p': 'Dunnage de toit, garde-corps, parapets, rénovation de la superstructure et réparation du système de toiture.',
    'svc.11.h': 'Ancrage & connexion',
    'svc.11.p': 'Conception d’ancrages en béton, connexions acier/bois, systèmes d’ancrage en maçonnerie.',
    'svc.12.h': 'Conception de coffrages',
    'svc.12.p': 'Coffrage de dalles, protection piétonne, et ingénierie de coffrage pour rénovation.',
    'svc.cat.forensic': 'Génie judiciaire',
    'svc.13.h': 'Enquête structurelle judiciaire',
    'svc.13.p': 'Enquête sur place des désordres structurels, effondrements ou mouvements inattendus pour déterminer la cause.',
    'svc.14.h': 'Analyse des défaillances & rapports d’expert',
    'svc.14.p': 'Analyse technique détaillée des défaillances structurelles pour les réclamations d’assurance, procédures judiciaires et litiges de conformité.',
    'svc.15.h': 'Témoignage & expertise',
    'svc.15.p': 'Témoignage d’ingénieur professionnel et services d’expert pour les litiges et arbitrages en construction.',
    'svc.cat.construction': 'Services de construction',
    'svc.16.h': 'Estimation des coûts',
    'svc.16.p': 'Quantitatifs précis et projections de coûts pour les lots structurels, aidant propriétaires et entrepreneurs à budgéter en toute confiance.',
    'svc.17.h': 'Planification de projet',
    'svc.17.p': 'Plannings de construction complets et analyse du chemin critique pour garder les projets structurels complexes sur la bonne voie.',
    'svc.18.h': 'Administration de la construction',
    'svc.18.p': 'Supervision d’ingénierie sur site et revue des plans d’atelier pour garantir la conformité structurelle.',
    'why.pill': 'Nos grandes valeurs',
    'why.h2': 'Pourquoi Asvakas ?',
    'why.cta': 'Faites connaissance avec nous →',
    'why.tagline': 'Approuvé par les propriétaires et promoteurs à travers le Canada, conçu pour la précision et la fiabilité des solutions structurelles.',
    'why.01.h': 'Qualité d’ingénierie éprouvée',
    'why.01.p': 'Notre équipe cumule plus de 35 ans d’expérience en ingénierie pour chaque inspection, conception et rénovation.',
    'why.02.h': 'Livraison à temps',
    'why.02.p': 'Nous respectons vos délais — chaque dépôt de permis, rapport d’inspection et livrable est réalisé dans les temps.',
    'why.03.h': 'Approche sécurité avant tout',
    'why.03.p': 'Nous suivons rigoureusement les codes CCO/NBC et les normes SST pour protéger votre propriété et tous les intervenants.',
    'why.04.h': 'Solutions d’ingénierie modernes',
    'why.04.p': 'Des perspectives innovantes appuyées par l’expérience — nous appliquons des méthodes efficaces et économiques.',
    'proj.featured.h2': 'Projets à la une',
    'proj.featured.sub': 'Un aperçu de notre savoir-faire, illustrant la qualité de chaque projet.',
    'proc.pill': 'Notre méthode',
    'proc.h2': 'Notre processus de travail',
    'proc.sub': 'Un processus éprouvé pour concrétiser vos idées, de la planification stratégique à la réalisation.',
    'proc.01.h': 'Consultation & planification',
    'proc.01.p': 'Comprendre vos besoins, budget et vision pour garantir l’alignement du projet avec vos objectifs.',
    'proc.02.h': 'Conception & architecture',
    'proc.02.p': 'Visualisation du projet avec une conception pratique et une précision structurelle conforme au CCO.',
    'proc.03.h': 'Construction & gestion',
    'proc.03.p': 'De la coordination de chantier au contrôle qualité, nous guidons l’exécution pour répondre à toutes les exigences.',
    'test.pill': 'Témoignages',
    'test.h2': 'Ce que disent nos clients',
    'test.sub': 'Découvrez comment nous avons transformé des exigences complexes en résultats concrets.',
    'test.1.quote': 'Asvakas a dépassé toutes les attentes. Leur équipe a transformé un dossier de conformité difficile en une livraison fluide et bien gérée.',
    'test.1.body': 'De l’inspection initiale à la validation finale, la communication était claire et chaque étape a été gérée avec précision.',
    'test.1.role': 'Client résidentiel, Toronto',
    'test.2.quote': 'De la consultation à la remise des clés, leurs ingénieurs étaient réactifs, pragmatiques et très compétents.',
    'test.2.body': 'Ils ont coordonné la rénovation de nos bureaux avec les entrepreneurs et les inspecteurs tout en maîtrisant les risques de calendrier.',
    'test.2.role': 'Promoteur commercial, Toronto',
    'test.3.quote': 'Leur stratégie d’ouvrages temporaires nous a évité de gros retards lors de l’excavation et du sous-œuvre.',
    'test.3.body': 'La documentation était claire, prête pour le permis et facile à exécuter pour notre équipe.',
    'test.3.role': 'Entrepreneur général, Ontario',
    'test.4.quote': 'Nous avons enfin trouvé un partenaire d’ingénierie alliant expertise technique et réalisme constructif.',
    'test.4.body': 'Leur équipe a anticipé les problèmes tôt et nous a aidés à prendre de meilleures décisions avant que les coûts n’augmentent.',
    'test.4.role': 'Gestionnaire immobilier, Vancouver',
    // ...add more keys as needed
  }
};

function applyLang(lang) {
  // Only English is available now
  lang = 'en';
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    if (translations[lang] && translations[lang][key]) {
      el.innerHTML = translations[lang][key];
    }
  });
  localStorage.setItem('lang', lang);
}

document.addEventListener('DOMContentLoaded', () => {
  applyLang('en');
});
